name: uopp_test
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.18.0 
  cupertino_icons: ^1.0.2
  dotted_border: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Black.ttf
        - asset: assets/fonts/CircularStd-BlackItalic.ttf
        - asset: assets/fonts/CircularStd-Bold.ttf
        - asset: assets/fonts/CircularStd-BoldItalic.ttf
        - asset: assets/fonts/CircularStd-Book.ttf
        - asset: assets/fonts/CircularStd-BookItalic.ttf
        - asset: assets/fonts/CircularStd-Medium.ttf
        - asset: assets/fonts/CircularStd-MediumItalic.ttf
